alvistack/v16.2.15
    git clean -xdf
    git submodule sync --recursive
    git submodule update --recursive --init
    git submodule foreach --recursive git checkout -- .
    git submodule foreach --recursive git clean -xdf
    ./make-debs.sh
    cp /tmp/release/Ubuntu/WORKDIR/*ceph*16.2.15*.{bz2,xz,dsc} /osc/home\:alvistack/ceph-ceph-16.2.15/
    cp ceph.spec /osc/home\:alvistack/ceph-ceph-16.2.15/ceph_16.2.15-1.spec
    cp ceph.rpmlintrc /osc/home\:alvistack/ceph-ceph-16.2.15/
    cp debian/patches/*.patch /osc/home\:alvistack/ceph-ceph-16.2.15/
    cp _constraints /osc/home\:alvistack/ceph-ceph-16.2.15/
    rm -rf /tmp/release/Ubuntu/WORKDIR

See https://github.com/spdk/spdk/issues/2637
See https://github.com/ceph/ceph/pull/47712
See https://github.com/ceph/ceph/pull/47982
See https://tracker.ceph.com/issues/56610
See https://build.opensuse.org/package/show/filesystems:ceph:quincy:upstream/ceph
See https://src.fedoraproject.org/rpms/ceph/tree/rawhide
See https://packages.ubuntu.com/source/lunar/ceph

Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -35,7 +35,7 @@ echo "version $version"
 # update submodules
 echo "updating submodules..."
 force=$(if git submodule usage 2>&1 | grep --quiet 'update.*--force'; then echo --force ; fi)
-if ! git submodule sync || ! git submodule update $force --init --recursive; then
+if ! git submodule sync || ! git submodule update $force --init --recursive --progress; then
     echo "Error: could not initialize submodule projects"
     echo "  Network connectivity might be required."
     exit 1
@@ -51,7 +51,7 @@ download_from() {
         url_base=$1
         shift
         if [ -z $url_base ]; then
-            echo "Error: failed to download $name."
+            echo "Error: failed to download $fname."
             exit
         fi
         url=$url_base/$fname
@@ -59,7 +59,7 @@ download_from() {
         if [ $? != 0 -o ! -e $fname ]; then
             echo "Download of $url failed"
         elif [ $(sha256sum $fname | awk '{print $1}') != $sha256 ]; then
-            echo "Error: failed to download $name: SHA256 mismatch."
+            echo "Error: failed to download $fname: SHA256 mismatch."
         else
             break
         fi
@@ -168,6 +168,19 @@ echo "including src/.git_version, ceph.spec"
 
 (git rev-parse HEAD ; echo $version) 2> /dev/null > src/.git_version
 
+if [ -r /etc/os-release ]; then
+    source /etc/os-release
+    case $ID in
+        opensuse*|suse|sles)
+            if [ "x$rpm_release" != "x0" ] ; then
+                rpm_release=$(echo $rpm_release | sed 's/.g/+g/')
+                rpm_version="${rpm_version}.${rpm_release}"
+                rpm_release="0"
+            fi
+            ;;
+    esac
+fi
+
 for spec in ceph.spec.in; do
     cat $spec |
         sed "s/@PROJECT_VERSION@/$rpm_version/g" |
@@ -178,12 +191,12 @@ ln -s . $outfile
 tar cvf $outfile.version.tar $outfile/src/.git_version $outfile/ceph.spec
 # NOTE: If you change this version number make sure the package is available
 # at the three URLs referenced below (may involve uploading to download.ceph.com)
-boost_version=1.73.0
-download_boost $boost_version 4eb3b8d442b426dc35346235c8733b5ae35ba431690e38c6a8263dce9fcbb402 \
-               https://boostorg.jfrog.io/artifactory/main/release/$boost_version/source \
-               https://downloads.sourceforge.net/project/boost/boost/$boost_version \
-               https://download.ceph.com/qa
-download_liburing 0.7 05d0cf8493d573c76b11abfcf34aabc7153affebe17ff95f9ae88b0de062a59d \
+boost_version=1.85.0
+download_boost $boost_version 7009fe1faa1697476bdc7027703a2badb84e849b7b0baad5086b087b971f8617 \
+               https://download.ceph.com/qa \
+               https://archives.boost.io/release/$boost_version/source
+download_liburing 2.5 456f5f882165630f0dc7b75e8fd53bd01a955d5d4720729b4323097e6e9f2a98 \
+                  https://github.com/axboe/liburing/archive \
                   https://git.kernel.dk/cgit/liburing/snapshot
 pmdk_version=1.10
 download_pmdk $pmdk_version 08dafcf94db5ac13fac9139c92225d9aa5f3724ea74beee4e6ca19a01a2eb20c \
