alvistack/v17.2.9
    git clean -xdf
    git submodule sync --recursive
    git submodule update --recursive --init
    git submodule foreach --recursive git checkout -- .
    git submodule foreach --recursive git clean -xdf
    ./make-debs.sh
    cp /tmp/release/Ubuntu/WORKDIR/*ceph*17.2.9*.{bz2,xz,dsc} /osc/home\:alvistack/ceph-ceph-17.2.9/
    cp ceph.spec /osc/home\:alvistack/ceph-ceph-17.2.9/ceph_17.2.9-1.spec
    cp ceph.rpmlintrc /osc/home\:alvistack/ceph-ceph-17.2.9/
    cp debian/patches/*.patch /osc/home\:alvistack/ceph-ceph-17.2.9/
    cp _constraints /osc/home\:alvistack/ceph-ceph-17.2.9/
    rm -rf /tmp/release/Ubuntu/WORKDIR

See https://github.com/spdk/spdk/issues/2637
See https://github.com/ceph/ceph/pull/47712
See https://github.com/ceph/ceph/pull/47982
See https://github.com/ceph/ceph/pull/53698
See https://tracker.ceph.com/issues/56610
See https://build.opensuse.org/package/show/filesystems:ceph:quincy:upstream/ceph
See https://src.fedoraproject.org/rpms/ceph/tree/rawhide
See https://packages.ubuntu.com/source/lunar/ceph

Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -35,7 +35,7 @@ echo "version $version"
 # update submodules
 echo "updating submodules..."
 force=$(if git submodule usage 2>&1 | grep --quiet 'update.*--force'; then echo --force ; fi)
-if ! git submodule sync || ! git submodule update $force --init --recursive; then
+if ! git submodule sync || ! git submodule update $force --init --recursive --progress; then
     echo "Error: could not initialize submodule projects"
     echo "  Network connectivity might be required."
     exit 1
@@ -51,7 +51,7 @@ download_from() {
         url_base=$1
         shift
         if [ -z $url_base ]; then
-            echo "Error: failed to download $name."
+            echo "Error: failed to download $fname."
             exit
         fi
         url=$url_base/$fname
@@ -59,7 +59,7 @@ download_from() {
         if [ $? != 0 -o ! -e $fname ]; then
             echo "Download of $url failed"
         elif [ $(sha256sum $fname | awk '{print $1}') != $sha256 ]; then
-            echo "Error: failed to download $name: SHA256 mismatch."
+            echo "Error: failed to download $fname: SHA256 mismatch."
         else
             break
         fi
@@ -132,7 +132,7 @@ build_dashboard_frontend() {
 
   $CURR_DIR/src/tools/setup-virtualenv.sh $TEMP_DIR
   $TEMP_DIR/bin/pip install nodeenv
-  $TEMP_DIR/bin/nodeenv --verbose -p --node=14.15.1
+  $TEMP_DIR/bin/nodeenv --verbose -p --node=18.17.0
   cd src/pybind/mgr/dashboard/frontend
 
   . $TEMP_DIR/bin/activate
@@ -191,12 +191,11 @@ ln -s . $outfile
 tar cvf $outfile.version.tar $outfile/src/.git_version $outfile/ceph.spec
 # NOTE: If you change this version number make sure the package is available
 # at the three URLs referenced below (may involve uploading to download.ceph.com)
-boost_version=1.75.0
-download_boost $boost_version 953db31e016db7bb207f11432bef7df100516eeb746843fa0486a222e3fd49cb \
-               https://boostorg.jfrog.io/artifactory/main/release/$boost_version/source \
-               https://downloads.sourceforge.net/project/boost/boost/$boost_version \
-               https://download.ceph.com/qa
-download_liburing 0.7 8e2842cfe947f3a443af301bdd6d034455536c38a455c7a700d0c1ad165a7543 \
+boost_version=1.85.0
+download_boost $boost_version 7009fe1faa1697476bdc7027703a2badb84e849b7b0baad5086b087b971f8617 \
+               https://download.ceph.com/qa \
+               https://archives.boost.io/release/$boost_version/source
+download_liburing 2.5 456f5f882165630f0dc7b75e8fd53bd01a955d5d4720729b4323097e6e9f2a98 \
                   https://github.com/axboe/liburing/archive \
                   https://git.kernel.dk/cgit/liburing/snapshot
 pmdk_version=1.10
